### ISSUE TITLE
Face Animations

### ISSUE THREAD

**Issue by tristen-shields** [JPsiInVR/organisation#157]
# Task description
For lip sync we need to create mouth shapes for every character. How these shapes should look is described in the [rhubarbs documentation](https://github.com/DanielSWolf/rhubarb-lip-sync#mouth-shapes).
Here's the image I used as a reference: 
<img src="https://user-images.githubusercontent.com/15947565/179817940-4ff312fc-c08e-4ee3-ba4c-0a83498045f9.png" width=50%>
It's crucial to keep placement of mouth shapes in each spritesheet consistent, so that it's possible to match numbers generated by the rhubarb library with the mouth shape. Here is the spritesheet for J/Psi 
<img src="https://user-images.githubusercontent.com/15947565/179818815-1fff4b36-7135-404c-816c-9bd4d24dd8f4.png" width=55%>

Eye sprites are at the bottom of the spritesheet. They have different cell shape. With eyes, I think it's enough to create three sprites (Open, partly closed, closed) to animate an eye blink.

Remaining cells can be filled with eye/mouth shapes to express emotions.

The templates for each character will be uploaded here, so whoever wants can work on it.
https://drive.google.com/drive/folders/1qVJnyz9IiaNU1s2nmEaC3vVWECbzBINO?usp=sharing

## Progress:
- [ ] J/Psi
  - [x] UV layout 
  - [x] Mouth shapes for lip sync
  - [ ] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotions
- [ ] News speaker
  - [x] UV layout 
  - [x] Mouth shapes for lip sync
  - [x] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotions
- [x] Up quark
  - [x] UV layout 
  - [x] Mouth shapes for lip sync
  - [x] ~~Eye shapes for blinking~~ He wears glasses
  - [x] ~~Eye~~/ Mouth shapes for emotions
- [ ] Down quark
  - [x] UV layout 
  - [x] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotions
- [ ] Bottom quark
  - [x] UV layout 
  - [x] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotions
- [ ] Top quark
  - [x] UV layout 
  - [x] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotion
- [ ] Charm quark
  - [x] UV layout 
  - [x] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotions
- [ ] Strange quark
  - [x] UV layout 
  - [x] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotions
- [ ] Neutron
  - [x] UV layout 
  - [x] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotions
- [ ] Proton
  - [x] UV layout 
  - [x] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotions

**Comment by Layfully** [comment]
# Task description
For lip sync we need to create mouth shapes for every character. How these shapes should look is decribed in the [rhubarbs documentation](https://github.com/DanielSWolf/rhubarb-lip-sync#mouth-shapes).
Here's the image I used as a reference: 
<img src="https://user-images.githubusercontent.com/15947565/179817940-4ff312fc-c08e-4ee3-ba4c-0a83498045f9.png" width=50%>
It's crucial to keep placement of mouth shapes in each spritesheet consistent, so that it's possible to match numbers generated by rhubarb library with mouth shape. Here is the spritesheet for J/Psi 
<img src="https://user-images.githubusercontent.com/15947565/179818815-1fff4b36-7135-404c-816c-9bd4d24dd8f4.png" width=55%>


Eye sprites are at the bottom of the spritesheet. They have different cell shape. With eyes I think it's enough to create three sprites (Open, partly closed, closed) to animate eye blink.

Remaining cells can be filled with eye/mouth shapes to express emotions.

## Progress:
- [ ] J/Psi
  - [x] Mouth shapes for lip sync
  - [ ] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotions
- [ ] News speaker
  - [ ] Mouth shapes for lip sync
  - [ ] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotions
- [ ] Up quark
  - [ ] Mouth shapes for lip sync
  - [ ] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotions
- [ ] Down quark
  - [ ] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotions
- [ ] Bottom quark
  - [ ] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotions
- [ ] Top quark
  - [ ] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotion
- [ ] Charm quark
  - [ ] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotions
- [ ] Strange quark
  - [ ] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotions
- [ ] Neutron
  - [ ] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotions
- [ ] Proton
  - [ ] Eye shapes for blinking
  - [ ] Eye/Mouth shapes for emotions
